#include "TelltaleDataModel.h"
#include "sm_telltalesm.h"
#include "sm_centerview.h"


TelltaleDataModel::TelltaleDataModel(int updateInterval, QObject *parent)
    : DataModel{updateInterval, parent}
{

}

void TelltaleDataModel::updateData()
{
    DATA_PROERTY_CHECK(leftTurnlamp)
    DATA_PROERTY_CHECK(rightTurnlamp)
    DATA_PROERTY_CHECK(hazardIsSignaling)
    DATA_PROERTY_CHECK(lowbeam)
    DATA_PROERTY_CHECK(highbeam)
    DATA_PROERTY_CHECK(Flashbeam)
    DATA_PROERTY_CHECK(positionlamp)
    DATA_PROERTY_CHECK(FrontFogLampSta)
    DATA_PROERTY_CHECK(rearFogLampSta)
    DATA_PROERTY_CHECK(autohighbeam)
    DATA_PROERTY_CHECK(DrvSeatbeltBucklestatus)
    DATA_PROERTY_CHECK(DrvSeatOccSta)
    DATA_PROERTY_CHECK(PAssSeatbeltBucklestatus)
    DATA_PROERTY_CHECK(PassSeatOccSta)
    DATA_PROERTY_CHECK(doorajarFL)
    DATA_PROERTY_CHECK(doorajarFR)
    DATA_PROERTY_CHECK(doorajarRL)
    DATA_PROERTY_CHECK(doorajarRR)
    DATA_PROERTY_CHECK(HoodSta)
    DATA_PROERTY_CHECK(TrunkSta)
    DATA_PROERTY_CHECK(FueldoorSta)
    DATA_PROERTY_CHECK(ChargeSta)
    DATA_PROERTY_CHECK(PEPSWarnSta)
    DATA_PROERTY_CHECK(TPMSSta)
    DATA_PROERTY_CHECK(TPMSPressureStaFL)
    DATA_PROERTY_CHECK(TPMSPressureStaFR)
    DATA_PROERTY_CHECK(TPMSPressureStaRL)
    DATA_PROERTY_CHECK(TPMSPressureStaRR)
    DATA_PROERTY_CHECK(SRSError)
    DATA_PROERTY_CHECK(lowbatterycharge)


    DATA_PROERTY_CHECK(HU_VehicleMainLamp)
    DATA_PROERTY_CHECK(ABSfailed)
    DATA_PROERTY_CHECK(PALAresponse)
    DATA_PROERTY_CHECK(ESPActiveSta)
    DATA_PROERTY_CHECK(ESCFailed)
    DATA_PROERTY_CHECK(HDCWorkSts)
    DATA_PROERTY_CHECK(ParkLampSta)
    DATA_PROERTY_CHECK(EBDFailed)
    DATA_PROERTY_CHECK(AVHSts)
    DATA_PROERTY_CHECK(BasicElecSteerFailed)
    DATA_PROERTY_CHECK(HU_brakeliquidlevel)
    DATA_PROERTY_CHECK(IMMOPCUauthen)
    DATA_PROERTY_CHECK(EPCwarn)


    DATA_PROERTY_CHECK(highCoolantTemperature)
    DATA_PROERTY_CHECK(lowFuel)
    DATA_PROERTY_CHECK(HU_MachineOilPre)
    DATA_PROERTY_CHECK(CruiseCtrlSta)
    DATA_PROERTY_CHECK(EngineSta)
    DATA_PROERTY_CHECK(TransSta)

    DATA_PROERTY_CHECK(InletConnctSta)
    DATA_PROERTY_CHECK(BatSOCRptWarning)
    DATA_PROERTY_CHECK(LimpHomeSta)
    DATA_PROERTY_CHECK(PwrTrainHighTempWrning)
    DATA_PROERTY_CHECK(PwrTrainConnectSta)
    DATA_PROERTY_CHECK(MotorHighTempWrning)
    DATA_PROERTY_CHECK(BMSSysFailSta)
    DATA_PROERTY_CHECK(DrvMotorSta)
    DATA_PROERTY_CHECK(PCUFailSta)
    DATA_PROERTY_CHECK(InsulationWrning)
    DATA_PROERTY_CHECK(VSPsta)
}


DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, leftTurnlamp, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, rightTurnlamp, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, hazardIsSignaling, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, lowbeam, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, highbeam, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, Flashbeam, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, positionlamp, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, FrontFogLampSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, rearFogLampSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, autohighbeam, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, DrvSeatbeltBucklestatus, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, DrvSeatOccSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, PAssSeatbeltBucklestatus, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, PassSeatOccSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, doorajarFL, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, doorajarFR, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, doorajarRL, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, doorajarRR, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, HoodSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, TrunkSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, FueldoorSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, ChargeSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, PEPSWarnSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, TPMSSta, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, TPMSPressureStaFL, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, TPMSPressureStaFR, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, TPMSPressureStaRL, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, TPMSPressureStaRR, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, SRSError, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, lowbatterycharge, bool)


DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, HU_VehicleMainLamp, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, ABSfailed, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, PALAresponse, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, ESPActiveSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, ESCFailed, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, HDCWorkSts, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, ParkLampSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, EBDFailed, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, AVHSts, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, BasicElecSteerFailed, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, HU_brakeliquidlevel, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, IMMOPCUauthen, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, EPCwarn, bool)


DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, highCoolantTemperature, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, lowFuel, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, HU_MachineOilPre, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, CruiseCtrlSta, int)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, EngineSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, TransSta, bool)

DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, InletConnctSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, BatSOCRptWarning, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, LimpHomeSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, PwrTrainHighTempWrning, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, PwrTrainConnectSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, MotorHighTempWrning, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, BMSSysFailSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, DrvMotorSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, PCUFailSta, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, InsulationWrning, bool)
DATA_PROPERTY_SIMPLE_IMPLEMENT(TelltaleDataModel, VSPsta, bool)
